DROP TABLE IF EXISTS 'account';
DROP TABLE IF EXISTS 'account_type';
DROP TABLE IF EXISTS 'account_state';
DROP TABLE IF EXISTS 'company';
DROP TABLE IF EXISTS 'users';
DROP TABLE IF EXISTS 'user_type';
